### PR TITLE
quick fix for issue #13

### PR DESCRIPTION
**Pull request by eviweb**
Signed-off-by: Eric Villard <dev@eviweb.fr>

### CODE REVIEW

**Comment by mehira-wooclap** [comment]
Hi @eviweb, thank you for your PR. Did you face any issues during an upgrade?

**Comment by mehira-wooclap** [comment]
Thank you @eviweb. We will deploy your fix in the next release.

**Comment by mehira-wooclap** [comment]
fixed in the next release.

**Comment by dfdeagle47** [comment]
Included as part of the new release [here](https://moodle.org/plugins/mod_wooclap/versions) and [here](https://moodle.org/plugins/mod_wooclap/2021122000/25693). Thank you for the PR!

**Pull request closed without merging**
